In [1]:
import pandas as pd
import json

In [2]:
SEASON = 2025
SUBMISSION_CSV = '2025_mov_my_submission.csv'

In [4]:
teams_df = pd.read_csv(f'march-machine-learning-mania-{SEASON}/MTeams.csv')
seeds_df = pd.read_csv(f'march-machine-learning-mania-{SEASON}/MNCAATourneySeeds.csv')
seeds_df = seeds_df[seeds_df['Season'] == SEASON]

In [3]:
df = pd.read_csv(SUBMISSION_CSV)
df.head()

   RowId Tournament  Bracket  Slot  Team
0      0          M        1   W16  W16a
1      1          M        1   X11  X11b
2      2          M        1   Y11  Y11a
3      3          M        1   Y16  Y16a
4      4          M        1  R1W1   W01

In [5]:
unique_slots = df['Slot'].unique()
slots = unique_slots

num_simulations = len(df['Bracket'].unique())
print(num_simulations)

100000

In [6]:
# test_df = df[df['Bracket'] <= 10]

# def concat_slot_team(group):
#     # Concatenate 'Slot' and 'Team' for each row, then join all for the group
#     return ' '.join(group['Slot'] + '_' + group['Team'])


# compressed_df = df.groupby('Bracket').apply(concat_slot_team)

# display(compressed_df)

# value_counts = compressed_df.value_counts()
# duplicates = value_counts[value_counts > 1]
# print(duplicates.head(5))
# print(duplicates.empty)

In [7]:
groups = df[df['Bracket'] <= 3].groupby('Bracket')
for bracket, bracket_df in groups:
    print(bracket)
    display(bracket_df)

1

    RowId Tournament  Bracket  Slot  Team
0       0          M        1   W16  W16a
1       1          M        1   X11  X11b
2       2          M        1   Y11  Y11a
3       3          M        1   Y16  Y16a
4       4          M        1  R1W1   W01
..    ...        ...      ...   ...   ...
62     62          M        1  R4Y1   Y03
63     63          M        1  R4Z1   Z01
64     64          M        1  R5WX   W06
65     65          M        1  R5YZ   Z01
66     66          M        1  R6CH   W06

[67 rows x 5 columns]

2

     RowId Tournament  Bracket  Slot  Team
67      67          M        2   W16  W16a
68      68          M        2   X11  X11b
69      69          M        2   Y11  Y11b
70      70          M        2   Y16  Y16b
71      71          M        2  R1W1   W01
..     ...        ...      ...   ...   ...
129    129          M        2  R4Y1   Y01
130    130          M        2  R4Z1   Z01
131    131          M        2  R5WX   X08
132    132          M        2  R5YZ   Y01
133    133          M        2  R6CH   Y01

[67 rows x 5 columns]

3

     RowId Tournament  Bracket  Slot  Team
134    134          M        3   W16  W16a
135    135          M        3   X11  X11b
136    136          M        3   Y11  Y11b
137    137          M        3   Y16  Y16a
138    138          M        3  R1W1   W01
..     ...        ...      ...   ...   ...
196    196          M        3  R4Y1   Y01
197    197          M        3  R4Z1   Z01
198    198          M        3  R5WX   W01
199    199          M        3  R5YZ   Z01
200    200          M        3  R6CH   W01

[67 rows x 5 columns]

In [8]:
display(seeds_df)

      Season Seed  TeamID
2558    2025  W01    1181
2559    2025  W02    1104
2560    2025  W03    1458
2561    2025  W04    1112
2562    2025  W05    1332
...      ...  ...     ...
2621    2025  Z12    1161
2622    2025  Z13    1213
2623    2025  Z14    1423
2624    2025  Z15    1303
2625    2025  Z16    1313

[68 rows x 3 columns]

In [9]:
# slots = ['R4W1', 'R4X1', 'R4Y1', 'R4Z1', 'R5WX', 'R5YZ', 'R6CH']
slots = df['Slot'].unique()
for slot in slots:
    filtered_df = df[(df['Slot'] == slot)]
    seed_counts = filtered_df['Team'].value_counts()
    print("Most occurrences for slot {}".format(slot))
    for (seed, occurrences) in seed_counts.head(4).items():
        seed_df = seeds_df[(seeds_df['Seed'] == seed)]
        if len(seed_df) > 1:
            print("seed_df contains more than one row")
        else:
            team_id = seed_df.iloc[0]['TeamID']
            team_name = teams_df[teams_df['TeamID'] == team_id].iloc[0]['TeamName']
            print(f"{team_name} wins {occurrences/num_simulations * 100:.2f}% of the time")
    print("")

Most occurrences for slot W16
American Univ wins 50.57% of the time
Mt St Mary's wins 49.43% of the time

Most occurrences for slot X11
Xavier wins 52.14% of the time
Texas wins 47.86% of the time

Most occurrences for slot Y11
North Carolina wins 58.49% of the time
San Diego St wins 41.51% of the time

Most occurrences for slot Y16
Alabama St wins 58.45% of the time
St Francis PA wins 41.55% of the time

Most occurrences for slot R1W1
Duke wins 99.70% of the time
Mt St Mary's wins 0.18% of the time
American Univ wins 0.11% of the time

Most occurrences for slot R1W2
Alabama wins 99.10% of the time
Robert Morris wins 0.90% of the time

Most occurrences for slot R1W3
Wisconsin wins 91.19% of the time
Montana wins 8.81% of the time

Most occurrences for slot R1W4
Arizona wins 92.18% of the time
Akron wins 7.81% of the time

Most occurrences for slot R1W5
Oregon wins 78.70% of the time
Liberty wins 21.30% of the time

Most occurrences for slot R1W6
BYU wins 60.63% of the time
VCU wins 39.37% of the time

Most occurrences for slot R1W7
St Mary's CA wins 51.94% of the time
Vanderbilt wins 48.05% of the time

Most occurrences for slot R1W8
Mississippi St wins 50.97% of the time
Baylor wins 49.03% of the time

Most occurrences for slot R1X1
Houston wins 99.71% of the time
SIUE wins 0.29% of the time

Most occurrences for slot R1X2
Tennessee wins 98.58% of the time
Wofford wins 1.42% of the time

Most occurrences for slot R1X3
Kentucky wins 89.44% of the time
Troy wins 10.56% of the time

Most occurrences for slot R1X4
Purdue wins 89.17% of the time
High Point wins 10.83% of the time

Most occurrences for slot R1X5
Clemson wins 73.61% of the time
McNeese St wins 26.39% of the time

Most occurrences for slot R1X6
Illinois wins 66.06% of the time
Xavier wins 18.97% of the time
Texas wins 14.96% of the time

Most occurrences for slot R1X7
UCLA wins 55.18% of the time
Utah St wins 44.82% of the time

Most occurrences for slot R1X8
Gonzaga wins 55.01% of the time
Georgia wins 44.99% of the time

Most occurrences for slot R1Y1
Auburn wins 99.89% of the time
Alabama St wins 0.08% of the time
St Francis PA wins 0.03% of the time

Most occurrences for slot R1Y2
Michigan St wins 98.49% of the time
Bryant wins 1.51% of the time

Most occurrences for slot R1Y3
Iowa St wins 89.68% of the time
Lipscomb wins 10.32% of the time

Most occurrences for slot R1Y4
Texas A&M wins 88.54% of the time
Yale wins 11.46% of the time

Most occurrences for slot R1Y5
Michigan wins 68.83% of the time
UC San Diego wins 31.18% of the time

Most occurrences for slot R1Y6
Mississippi wins 58.80% of the time
North Carolina wins 25.92% of the time
San Diego St wins 15.28% of the time

Most occurrences for slot R1Y7
Marquette wins 66.94% of the time
New Mexico wins 33.06% of the time

Most occurrences for slot R1Y8
Louisville wins 57.95% of the time
Creighton wins 42.05% of the time

Most occurrences for slot R1Z1
Florida wins 99.83% of the time
Norfolk St wins 0.17% of the time

Most occurrences for slot R1Z2
St John's wins 95.09% of the time
NE Omaha wins 4.91% of the time

Most occurrences for slot R1Z3
Texas Tech wins 90.70% of the time
UNC Wilmington wins 9.30% of the time

Most occurrences for slot R1Z4
Maryland wins 87.03% of the time
Grand Canyon wins 12.97% of the time

Most occurrences for slot R1Z5
Memphis wins 53.20% of the time
Colorado St wins 46.80% of the time

Most occurrences for slot R1Z6
Missouri wins 62.03% of the time
Drake wins 37.97% of the time

Most occurrences for slot R1Z7
Kansas wins 60.97% of the time
Arkansas wins 39.03% of the time

Most occurrences for slot R1Z8
Connecticut wins 51.23% of the time
Oklahoma wins 48.77% of the time

Most occurrences for slot R2W1
Duke wins 83.75% of the time
Mississippi St wins 10.72% of the time
Baylor wins 5.51% of the time
American Univ wins 0.01% of the time

Most occurrences for slot R2W2
Alabama wins 65.30% of the time
St Mary's CA wins 22.09% of the time
Vanderbilt wins 12.53% of the time
Robert Morris wins 0.08% of the time

Most occurrences for slot R2W3
Wisconsin wins 52.83% of the time
BYU wins 32.06% of the time
VCU wins 13.81% of the time
Montana wins 1.30% of the time

Most occurrences for slot R2W4
Arizona wins 50.05% of the time
Oregon wins 43.29% of the time
Liberty wins 5.95% of the time
Akron wins 0.71% of the time

Most occurrences for slot R2X1
Houston wins 81.34% of the time
Gonzaga wins 12.31% of the time
Georgia wins 6.34% of the time
SIUE wins 0.01% of the time

Most occurrences for slot R2X2
Tennessee wins 72.55% of the time
UCLA wins 15.46% of the time
Utah St wins 11.85% of the time
Wofford wins 0.14% of the time

Most occurrences for slot R2X3
Kentucky wins 52.08% of the time
Illinois wins 33.37% of the time
Xavier wins 7.70% of the time
Texas wins 5.19% of the time

Most occurrences for slot R2X4
Purdue wins 51.08% of the time
Clemson wins 38.10% of the time
McNeese St wins 8.47% of the time
High Point wins 2.34% of the time

Most occurrences for slot R2Y1
Auburn wins 73.71% of the time
Louisville wins 18.07% of the time
Creighton wins 8.22% of the time
St Francis PA wins 0.00% of the time

Most occurrences for slot R2Y2
Michigan St wins 67.69% of the time
Marquette wins 22.61% of the time
New Mexico wins 9.65% of the time
Bryant wins 0.06% of the time

Most occurrences for slot R2Y3
Iowa St wins 53.43% of the time
Mississippi wins 30.26% of the time
North Carolina wins 9.59% of the time
San Diego St wins 5.27% of the time

Most occurrences for slot R2Y4
Texas A&M wins 48.68% of the time
Michigan wins 37.22% of the time
UC San Diego wins 12.90% of the time
Yale wins 1.20% of the time

Most occurrences for slot R2Z1
Florida wins 83.52% of the time
Oklahoma wins 8.31% of the time
Connecticut wins 8.16% of the time
Norfolk St wins 0.01% of the time

Most occurrences for slot R2Z2
St John's wins 49.83% of the time
Kansas wins 31.70% of the time
Arkansas wins 18.12% of the time
NE Omaha wins 0.35% of the time

Most occurrences for slot R2Z3
Texas Tech wins 59.37% of the time
Missouri wins 25.91% of the time
Drake wins 12.67% of the time
UNC Wilmington wins 2.06% of the time

Most occurrences for slot R2Z4
Maryland wins 57.71% of the time
Memphis wins 21.45% of the time
Colorado St wins 17.98% of the time
Grand Canyon wins 2.86% of the time

Most occurrences for slot R3W1
Duke wins 60.16% of the time
Oregon wins 16.85% of the time
Arizona wins 14.92% of the time
Mississippi St wins 5.18% of the time

Most occurrences for slot R3W2
Alabama wins 39.12% of the time
Wisconsin wins 26.10% of the time
BYU wins 14.85% of the time
St Mary's CA wins 11.10% of the time

Most occurrences for slot R3X1
Houston wins 66.51% of the time
Purdue wins 13.39% of the time
Clemson wins 9.81% of the time
Gonzaga wins 6.64% of the time

Most occurrences for slot R3X2
Tennessee wins 45.83% of the time
Kentucky wins 24.34% of the time
Illinois wins 13.33% of the time
UCLA wins 8.00% of the time

Most occurrences for slot R3Y1
Auburn wins 54.28% of the time
Texas A&M wins 16.07% of the time
Michigan wins 13.42% of the time
Louisville wins 10.27% of the time

Most occurrences for slot R3Y2
Michigan St wins 40.22% of the time
Iowa St wins 27.15% of the time
Mississippi wins 14.49% of the time
Marquette wins 9.76% of the time

Most occurrences for slot R3Z1
Florida wins 70.15% of the time
Maryland wins 15.85% of the time
Oklahoma wins 3.66% of the time
Memphis wins 3.58% of the time

Most occurrences for slot R3Z2
Texas Tech wins 36.24% of the time
St John's wins 24.04% of the time
Missouri wins 14.53% of the time
Kansas wins 14.22% of the time

Most occurrences for slot R4W1
Duke wins 41.96% of the time
Alabama wins 19.54% of the time
Wisconsin wins 9.50% of the time
Oregon wins 8.17% of the time

Most occurrences for slot R4X1
Houston wins 42.86% of the time
Tennessee wins 25.78% of the time
Kentucky wins 9.13% of the time
Purdue wins 5.82% of the time

Most occurrences for slot R4Y1
Auburn wins 40.69% of the time
Michigan St wins 16.81% of the time
Iowa St wins 9.91% of the time
Texas A&M wins 7.99% of the time

Most occurrences for slot R4Z1
Florida wins 54.11% of the time
Texas Tech wins 14.40% of the time
Maryland wins 7.96% of the time
St John's wins 7.89% of the time

Most occurrences for slot R5WX
Houston wins 25.84% of the time
Duke wins 24.91% of the time
Tennessee wins 13.83% of the time
Alabama wins 9.86% of the time

Most occurrences for slot R5YZ
Florida wins 35.55% of the time
Auburn wins 24.59% of the time
Michigan St wins 6.76% of the time
Texas Tech wins 6.71% of the time

Most occurrences for slot R6CH
Florida wins 20.70% of the time
Houston wins 15.32% of the time
Duke wins 15.07% of the time
Auburn wins 14.02% of the time

In [17]:
def show_results(submission_csv, slots=[]):
    df = pd.read_csv(submission_csv)
    if len(slots) == 0:
        slots = slots = df['Slot'].unique()

    for slot in slots:
        filtered_df = df[(df['Slot'] == slot)]
        seed_counts = filtered_df['Team'].value_counts()
        print("Most occurrences for slot {}".format(slot))
        for (seed, occurrences) in seed_counts.head(4).items():
            seed_df = seeds_df[(seeds_df['Seed'] == seed)]
            if len(seed_df) > 1:
                print("seed_df contains more than one row")
            else:
                team_id = seed_df.iloc[0]['TeamID']
                team_name = teams_df[teams_df['TeamID'] == team_id].iloc[0]['TeamName']
                print(f"{team_name} wins {occurrences/num_simulations * 100:.2f}% of the time")
        print("")

In [21]:
show_results('2025_mov_my_submission.csv')

Most occurrences for slot W16
American Univ wins 50.57% of the time
Mt St Mary's wins 49.43% of the time

Most occurrences for slot X11
Xavier wins 52.14% of the time
Texas wins 47.86% of the time

Most occurrences for slot Y11
North Carolina wins 58.49% of the time
San Diego St wins 41.51% of the time

Most occurrences for slot Y16
Alabama St wins 58.45% of the time
St Francis PA wins 41.55% of the time

Most occurrences for slot R1W1
Duke wins 99.70% of the time
Mt St Mary's wins 0.18% of the time
American Univ wins 0.11% of the time

Most occurrences for slot R1W2
Alabama wins 99.10% of the time
Robert Morris wins 0.90% of the time

Most occurrences for slot R1W3
Wisconsin wins 91.19% of the time
Montana wins 8.81% of the time

Most occurrences for slot R1W4
Arizona wins 92.18% of the time
Akron wins 7.81% of the time

Most occurrences for slot R1W5
Oregon wins 78.70% of the time
Liberty wins 21.30% of the time

Most occurrences for slot R1W6
BYU wins 60.63% of the time
VCU wins 39.37% of the time

Most occurrences for slot R1W7
St Mary's CA wins 51.94% of the time
Vanderbilt wins 48.05% of the time

Most occurrences for slot R1W8
Mississippi St wins 50.97% of the time
Baylor wins 49.03% of the time

Most occurrences for slot R1X1
Houston wins 99.71% of the time
SIUE wins 0.29% of the time

Most occurrences for slot R1X2
Tennessee wins 98.58% of the time
Wofford wins 1.42% of the time

Most occurrences for slot R1X3
Kentucky wins 89.44% of the time
Troy wins 10.56% of the time

Most occurrences for slot R1X4
Purdue wins 89.17% of the time
High Point wins 10.83% of the time

Most occurrences for slot R1X5
Clemson wins 73.61% of the time
McNeese St wins 26.39% of the time

Most occurrences for slot R1X6
Illinois wins 66.06% of the time
Xavier wins 18.97% of the time
Texas wins 14.96% of the time

Most occurrences for slot R1X7
UCLA wins 55.18% of the time
Utah St wins 44.82% of the time

Most occurrences for slot R1X8
Gonzaga wins 55.01% of the time
Georgia wins 44.99% of the time

Most occurrences for slot R1Y1
Auburn wins 99.89% of the time
Alabama St wins 0.08% of the time
St Francis PA wins 0.03% of the time

Most occurrences for slot R1Y2
Michigan St wins 98.49% of the time
Bryant wins 1.51% of the time

Most occurrences for slot R1Y3
Iowa St wins 89.68% of the time
Lipscomb wins 10.32% of the time

Most occurrences for slot R1Y4
Texas A&M wins 88.54% of the time
Yale wins 11.46% of the time

Most occurrences for slot R1Y5
Michigan wins 68.83% of the time
UC San Diego wins 31.18% of the time

Most occurrences for slot R1Y6
Mississippi wins 58.80% of the time
North Carolina wins 25.92% of the time
San Diego St wins 15.28% of the time

Most occurrences for slot R1Y7
Marquette wins 66.94% of the time
New Mexico wins 33.06% of the time

Most occurrences for slot R1Y8
Louisville wins 57.95% of the time
Creighton wins 42.05% of the time

Most occurrences for slot R1Z1
Florida wins 99.83% of the time
Norfolk St wins 0.17% of the time

Most occurrences for slot R1Z2
St John's wins 95.09% of the time
NE Omaha wins 4.91% of the time

Most occurrences for slot R1Z3
Texas Tech wins 90.70% of the time
UNC Wilmington wins 9.30% of the time

Most occurrences for slot R1Z4
Maryland wins 87.03% of the time
Grand Canyon wins 12.97% of the time

Most occurrences for slot R1Z5
Memphis wins 53.20% of the time
Colorado St wins 46.80% of the time

Most occurrences for slot R1Z6
Missouri wins 62.03% of the time
Drake wins 37.97% of the time

Most occurrences for slot R1Z7
Kansas wins 60.97% of the time
Arkansas wins 39.03% of the time

Most occurrences for slot R1Z8
Connecticut wins 51.23% of the time
Oklahoma wins 48.77% of the time

Most occurrences for slot R2W1
Duke wins 83.75% of the time
Mississippi St wins 10.72% of the time
Baylor wins 5.51% of the time
American Univ wins 0.01% of the time

Most occurrences for slot R2W2
Alabama wins 65.30% of the time
St Mary's CA wins 22.09% of the time
Vanderbilt wins 12.53% of the time
Robert Morris wins 0.08% of the time

Most occurrences for slot R2W3
Wisconsin wins 52.83% of the time
BYU wins 32.06% of the time
VCU wins 13.81% of the time
Montana wins 1.30% of the time

Most occurrences for slot R2W4
Arizona wins 50.05% of the time
Oregon wins 43.29% of the time
Liberty wins 5.95% of the time
Akron wins 0.71% of the time

Most occurrences for slot R2X1
Houston wins 81.34% of the time
Gonzaga wins 12.31% of the time
Georgia wins 6.34% of the time
SIUE wins 0.01% of the time

Most occurrences for slot R2X2
Tennessee wins 72.55% of the time
UCLA wins 15.46% of the time
Utah St wins 11.85% of the time
Wofford wins 0.14% of the time

Most occurrences for slot R2X3
Kentucky wins 52.08% of the time
Illinois wins 33.37% of the time
Xavier wins 7.70% of the time
Texas wins 5.19% of the time

Most occurrences for slot R2X4
Purdue wins 51.08% of the time
Clemson wins 38.10% of the time
McNeese St wins 8.47% of the time
High Point wins 2.34% of the time

Most occurrences for slot R2Y1
Auburn wins 73.71% of the time
Louisville wins 18.07% of the time
Creighton wins 8.22% of the time
St Francis PA wins 0.00% of the time

Most occurrences for slot R2Y2
Michigan St wins 67.69% of the time
Marquette wins 22.61% of the time
New Mexico wins 9.65% of the time
Bryant wins 0.06% of the time

Most occurrences for slot R2Y3
Iowa St wins 53.43% of the time
Mississippi wins 30.26% of the time
North Carolina wins 9.59% of the time
San Diego St wins 5.27% of the time

Most occurrences for slot R2Y4
Texas A&M wins 48.68% of the time
Michigan wins 37.22% of the time
UC San Diego wins 12.90% of the time
Yale wins 1.20% of the time

Most occurrences for slot R2Z1
Florida wins 83.52% of the time
Oklahoma wins 8.31% of the time
Connecticut wins 8.16% of the time
Norfolk St wins 0.01% of the time

Most occurrences for slot R2Z2
St John's wins 49.83% of the time
Kansas wins 31.70% of the time
Arkansas wins 18.12% of the time
NE Omaha wins 0.35% of the time

Most occurrences for slot R2Z3
Texas Tech wins 59.37% of the time
Missouri wins 25.91% of the time
Drake wins 12.67% of the time
UNC Wilmington wins 2.06% of the time

Most occurrences for slot R2Z4
Maryland wins 57.71% of the time
Memphis wins 21.45% of the time
Colorado St wins 17.98% of the time
Grand Canyon wins 2.86% of the time

Most occurrences for slot R3W1
Duke wins 60.16% of the time
Oregon wins 16.85% of the time
Arizona wins 14.92% of the time
Mississippi St wins 5.18% of the time

Most occurrences for slot R3W2
Alabama wins 39.12% of the time
Wisconsin wins 26.10% of the time
BYU wins 14.85% of the time
St Mary's CA wins 11.10% of the time

Most occurrences for slot R3X1
Houston wins 66.51% of the time
Purdue wins 13.39% of the time
Clemson wins 9.81% of the time
Gonzaga wins 6.64% of the time

Most occurrences for slot R3X2
Tennessee wins 45.83% of the time
Kentucky wins 24.34% of the time
Illinois wins 13.33% of the time
UCLA wins 8.00% of the time

Most occurrences for slot R3Y1
Auburn wins 54.28% of the time
Texas A&M wins 16.07% of the time
Michigan wins 13.42% of the time
Louisville wins 10.27% of the time

Most occurrences for slot R3Y2
Michigan St wins 40.22% of the time
Iowa St wins 27.15% of the time
Mississippi wins 14.49% of the time
Marquette wins 9.76% of the time

Most occurrences for slot R3Z1
Florida wins 70.15% of the time
Maryland wins 15.85% of the time
Oklahoma wins 3.66% of the time
Memphis wins 3.58% of the time

Most occurrences for slot R3Z2
Texas Tech wins 36.24% of the time
St John's wins 24.04% of the time
Missouri wins 14.53% of the time
Kansas wins 14.22% of the time

Most occurrences for slot R4W1
Duke wins 41.96% of the time
Alabama wins 19.54% of the time
Wisconsin wins 9.50% of the time
Oregon wins 8.17% of the time

Most occurrences for slot R4X1
Houston wins 42.86% of the time
Tennessee wins 25.78% of the time
Kentucky wins 9.13% of the time
Purdue wins 5.82% of the time

Most occurrences for slot R4Y1
Auburn wins 40.69% of the time
Michigan St wins 16.81% of the time
Iowa St wins 9.91% of the time
Texas A&M wins 7.99% of the time

Most occurrences for slot R4Z1
Florida wins 54.11% of the time
Texas Tech wins 14.40% of the time
Maryland wins 7.96% of the time
St John's wins 7.89% of the time

Most occurrences for slot R5WX
Houston wins 25.84% of the time
Duke wins 24.91% of the time
Tennessee wins 13.83% of the time
Alabama wins 9.86% of the time

Most occurrences for slot R5YZ
Florida wins 35.55% of the time
Auburn wins 24.59% of the time
Michigan St wins 6.76% of the time
Texas Tech wins 6.71% of the time

Most occurrences for slot R6CH
Florida wins 20.70% of the time
Houston wins 15.32% of the time
Duke wins 15.07% of the time
Auburn wins 14.02% of the time

In [20]:
show_results('2025_win_my_submission.csv')

Most occurrences for slot W16
American Univ wins 50.74% of the time
Mt St Mary's wins 49.26% of the time

Most occurrences for slot X11
Xavier wins 52.05% of the time
Texas wins 47.95% of the time

Most occurrences for slot Y11
North Carolina wins 58.60% of the time
San Diego St wins 41.39% of the time

Most occurrences for slot Y16
Alabama St wins 58.29% of the time
St Francis PA wins 41.71% of the time

Most occurrences for slot R1W1
Duke wins 99.73% of the time
Mt St Mary's wins 0.19% of the time
American Univ wins 0.08% of the time

Most occurrences for slot R1W2
Alabama wins 99.07% of the time
Robert Morris wins 0.93% of the time

Most occurrences for slot R1W3
Wisconsin wins 91.29% of the time
Montana wins 8.71% of the time

Most occurrences for slot R1W4
Arizona wins 92.22% of the time
Akron wins 7.78% of the time

Most occurrences for slot R1W5
Oregon wins 78.70% of the time
Liberty wins 21.30% of the time

Most occurrences for slot R1W6
BYU wins 60.69% of the time
VCU wins 39.31% of the time

Most occurrences for slot R1W7
St Mary's CA wins 51.66% of the time
Vanderbilt wins 48.34% of the time

Most occurrences for slot R1W8
Mississippi St wins 50.96% of the time
Baylor wins 49.04% of the time

Most occurrences for slot R1X1
Houston wins 99.71% of the time
SIUE wins 0.29% of the time

Most occurrences for slot R1X2
Tennessee wins 98.62% of the time
Wofford wins 1.38% of the time

Most occurrences for slot R1X3
Kentucky wins 89.44% of the time
Troy wins 10.56% of the time

Most occurrences for slot R1X4
Purdue wins 89.12% of the time
High Point wins 10.88% of the time

Most occurrences for slot R1X5
Clemson wins 73.47% of the time
McNeese St wins 26.53% of the time

Most occurrences for slot R1X6
Illinois wins 66.16% of the time
Xavier wins 18.96% of the time
Texas wins 14.88% of the time

Most occurrences for slot R1X7
UCLA wins 55.40% of the time
Utah St wins 44.60% of the time

Most occurrences for slot R1X8
Gonzaga wins 55.38% of the time
Georgia wins 44.62% of the time

Most occurrences for slot R1Y1
Auburn wins 99.88% of the time
Alabama St wins 0.08% of the time
St Francis PA wins 0.04% of the time

Most occurrences for slot R1Y2
Michigan St wins 98.45% of the time
Bryant wins 1.55% of the time

Most occurrences for slot R1Y3
Iowa St wins 89.74% of the time
Lipscomb wins 10.26% of the time

Most occurrences for slot R1Y4
Texas A&M wins 88.61% of the time
Yale wins 11.39% of the time

Most occurrences for slot R1Y5
Michigan wins 68.38% of the time
UC San Diego wins 31.62% of the time

Most occurrences for slot R1Y6
Mississippi wins 58.73% of the time
North Carolina wins 26.08% of the time
San Diego St wins 15.19% of the time

Most occurrences for slot R1Y7
Marquette wins 66.79% of the time
New Mexico wins 33.21% of the time

Most occurrences for slot R1Y8
Louisville wins 57.33% of the time
Creighton wins 42.67% of the time

Most occurrences for slot R1Z1
Florida wins 99.83% of the time
Norfolk St wins 0.17% of the time

Most occurrences for slot R1Z2
St John's wins 95.10% of the time
NE Omaha wins 4.90% of the time

Most occurrences for slot R1Z3
Texas Tech wins 90.95% of the time
UNC Wilmington wins 9.05% of the time

Most occurrences for slot R1Z4
Maryland wins 87.19% of the time
Grand Canyon wins 12.81% of the time

Most occurrences for slot R1Z5
Memphis wins 53.56% of the time
Colorado St wins 46.44% of the time

Most occurrences for slot R1Z6
Missouri wins 61.67% of the time
Drake wins 38.33% of the time

Most occurrences for slot R1Z7
Kansas wins 60.68% of the time
Arkansas wins 39.32% of the time

Most occurrences for slot R1Z8
Connecticut wins 51.27% of the time
Oklahoma wins 48.73% of the time

Most occurrences for slot R2W1
Duke wins 83.87% of the time
Mississippi St wins 10.76% of the time
Baylor wins 5.35% of the time
American Univ wins 0.01% of the time

Most occurrences for slot R2W2
Alabama wins 65.25% of the time
St Mary's CA wins 21.94% of the time
Vanderbilt wins 12.72% of the time
Robert Morris wins 0.09% of the time

Most occurrences for slot R2W3
Wisconsin wins 52.77% of the time
BYU wins 31.97% of the time
VCU wins 14.03% of the time
Montana wins 1.22% of the time

Most occurrences for slot R2W4
Arizona wins 50.36% of the time
Oregon wins 43.17% of the time
Liberty wins 5.71% of the time
Akron wins 0.76% of the time

Most occurrences for slot R2X1
Houston wins 81.29% of the time
Gonzaga wins 12.44% of the time
Georgia wins 6.26% of the time
SIUE wins 0.01% of the time

Most occurrences for slot R2X2
Tennessee wins 72.78% of the time
UCLA wins 15.36% of the time
Utah St wins 11.73% of the time
Wofford wins 0.13% of the time

Most occurrences for slot R2X3
Kentucky wins 51.81% of the time
Illinois wins 33.63% of the time
Xavier wins 7.78% of the time
Texas wins 5.07% of the time

Most occurrences for slot R2X4
Purdue wins 50.90% of the time
Clemson wins 38.06% of the time
McNeese St wins 8.72% of the time
High Point wins 2.33% of the time

Most occurrences for slot R2Y1
Auburn wins 73.76% of the time
Louisville wins 17.90% of the time
Creighton wins 8.34% of the time
Alabama St wins 0.00% of the time

Most occurrences for slot R2Y2
Michigan St wins 67.88% of the time
Marquette wins 22.38% of the time
New Mexico wins 9.68% of the time
Bryant wins 0.07% of the time

Most occurrences for slot R2Y3
Iowa St wins 53.58% of the time
Mississippi wins 30.16% of the time
North Carolina wins 9.67% of the time
San Diego St wins 5.10% of the time

Most occurrences for slot R2Y4
Texas A&M wins 48.46% of the time
Michigan wins 37.18% of the time
UC San Diego wins 13.18% of the time
Yale wins 1.18% of the time

Most occurrences for slot R2Z1
Florida wins 83.20% of the time
Connecticut wins 8.44% of the time
Oklahoma wins 8.33% of the time
Norfolk St wins 0.02% of the time

Most occurrences for slot R2Z2
St John's wins 49.78% of the time
Kansas wins 31.42% of the time
Arkansas wins 18.43% of the time
NE Omaha wins 0.37% of the time

Most occurrences for slot R2Z3
Texas Tech wins 59.40% of the time
Missouri wins 25.91% of the time
Drake wins 12.72% of the time
UNC Wilmington wins 1.96% of the time

Most occurrences for slot R2Z4
Maryland wins 57.84% of the time
Memphis wins 21.51% of the time
Colorado St wins 17.88% of the time
Grand Canyon wins 2.77% of the time

Most occurrences for slot R3W1
Duke wins 59.82% of the time
Oregon wins 16.81% of the time
Arizona wins 15.28% of the time
Mississippi St wins 5.18% of the time

Most occurrences for slot R3W2
Alabama wins 39.08% of the time
Wisconsin wins 25.97% of the time
BYU wins 14.88% of the time
St Mary's CA wins 11.16% of the time

Most occurrences for slot R3X1
Houston wins 66.30% of the time
Purdue wins 13.51% of the time
Clemson wins 9.88% of the time
Gonzaga wins 6.64% of the time

Most occurrences for slot R3X2
Tennessee wins 46.24% of the time
Kentucky wins 24.05% of the time
Illinois wins 13.36% of the time
UCLA wins 7.96% of the time

Most occurrences for slot R3Y1
Auburn wins 54.33% of the time
Texas A&M wins 15.94% of the time
Michigan wins 13.53% of the time
Louisville wins 10.05% of the time

Most occurrences for slot R3Y2
Michigan St wins 40.35% of the time
Iowa St wins 27.24% of the time
Mississippi wins 14.43% of the time
Marquette wins 9.68% of the time

Most occurrences for slot R3Z1
Florida wins 70.05% of the time
Maryland wins 15.90% of the time
Oklahoma wins 3.72% of the time
Connecticut wins 3.60% of the time

Most occurrences for slot R3Z2
Texas Tech wins 36.33% of the time
St John's wins 23.86% of the time
Missouri wins 14.42% of the time
Kansas wins 14.18% of the time

Most occurrences for slot R4W1
Duke wins 41.76% of the time
Alabama wins 19.57% of the time
Wisconsin wins 9.60% of the time
Oregon wins 8.05% of the time

Most occurrences for slot R4X1
Houston wins 42.66% of the time
Tennessee wins 25.91% of the time
Kentucky wins 8.96% of the time
Purdue wins 5.97% of the time

Most occurrences for slot R4Y1
Auburn wins 40.67% of the time
Michigan St wins 16.94% of the time
Iowa St wins 10.07% of the time
Texas A&M wins 7.98% of the time

Most occurrences for slot R4Z1
Florida wins 54.03% of the time
Texas Tech wins 14.33% of the time
Maryland wins 8.09% of the time
St John's wins 7.85% of the time

Most occurrences for slot R5WX
Houston wins 25.90% of the time
Duke wins 24.86% of the time
Tennessee wins 13.90% of the time
Alabama wins 9.83% of the time

Most occurrences for slot R5YZ
Florida wins 35.35% of the time
Auburn wins 24.58% of the time
Michigan St wins 6.94% of the time
Texas Tech wins 6.69% of the time

Most occurrences for slot R6CH
Florida wins 20.48% of the time
Houston wins 15.39% of the time
Duke wins 15.06% of the time
Auburn wins 14.12% of the time